language: objective-c
sudo: false
osx_image: xcode8.3

matrix:
  include:
    - os: osx
      env: ACTION=test_ios10
    - os: osx
      env: ACTION=test_ios9
    - os: osx
      env: ACTION=test_macos
    - os: osx
      env: ACTION=test_tvos10
    - os: osx
      env: ACTION=build_watchos
    - os: osx
      env: ACTION=pod_lint
    - os: osx
      env: ACTION=carthage_build
    - os: osx
      env: ACTION=spm_macos

script:
  - bundle exec fastlane $ACTION
